export const FETCH_RENTAL_INIT = "FETCH_RENTAL_INIT";
export const FETCH_RENTAL_FAIL = "FETCH_RENTAL_FAIL";

export const FETCH_RENTALS_SUCCESS = "FETCH_RENTALS_SUCCESS";
export const FETCH_RENTAL_BY_ID = "FETCH_RENTAL_BY_ID";
export const FETCH_RENTAL_BY_ID_INIT = "FETCH_RENTAL_BY_ID_INIT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const FETCH_USER_BOOKINGS_INIT = "FETCH_USER_BOOKING_INIT";
export const FETCH_USER_BOOKINGS_SUCCESS = "FETCH_USER_BOOKING_SUCCESS";
export const FETCH_USER_BOOKING_FAILURE = "FETCH_USER_BOOKING_FAILURE";

export const UPDATE_RENTAL_SUCCESS = "UPDATE_RENTAL_SUCCESS";
export const UPDATE_RENTAL_FAILURE = "UPDATE_RENTAL_FAILURE";
export const RESET_RENTAL_ERRORS = "RESET_RENTAL_ERRORS";

export const RELOAD_MAP = "RELOAD_MAP";
export const RELOAD_MAP_FINISH = "RELOAD_MAP_FINISH";
